<?php /* JQ_StyleCSS - Critical Path CSS */ ?>
<?php if(Mage::helper('stylecss')->isEnabledCriticalPathCSS()): ?>
    <style id="critical-path">
        <?php echo Mage::helper('stylecss')->getCriticalStyles(); ?>
    </style>
<?php endif; ?>
<?php /* end JQ_StyleCSS - Critical Path CSS */ ?>

<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<?php /* JQ_StyleCSS - Custom Theme Style */ ?>
<?php if(Mage::helper('stylecss')->isEnabledCustomStyles()): ?>
    <style id="custom-styles">
        <?php echo Mage::helper('stylecss')->getCustomStyles(); ?>
    </style>
<?php endif; ?>
<?php /* end JQ_StyleCSS - Custom Theme Style */ ?>
